version: '3.7'


# Declare the containers to run in the compose stack
services:
  nginx:
    image: nginx
    restart: unless-stopped
    # Copy config files
    volumes:
      - ./secrets/domain.crt:/run/secrets/domain.crt
      - ./secrets/domain.key:/run/secrets/domain.key
      - ./nginx/legacy.conf.template:/etc/nginx/templates/default.conf.template
    # Expose https and http ports. All http traffic will be redirected to https by nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - legacy.env

  legacy:
    build:
      context: legacy_application/
      dockerfile: Dockerfile
    depends_on:
      - nginx
    restart: unless-stopped
    # Mount the site files into the container into the container (host_path:container_path:read-only)
    # changed to have full access
    volumes:
      - "./prd:/opt/library/prd"
    env_file:
      - legacy.env

